---
title: "Hello World"
author: "mikefc@coolbutuseless.com"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include = FALSE}
suppressPackageStartupMessages({
  library(dplyr)
  library(ggplot2)
  library(r64)  
})

knitr::opts_chunk$set(echo=FALSE)
```


```{r}
#-----------------------------------------------------------------------------
#' Create a character set that wipes from side to side
#-----------------------------------------------------------------------------
create_sideswipe_charset <- function() {
  charset <- as.integer(c(0x00, 0x01, 0x01, 0x03, 0x03, 0x07, 0x07, 0x0f,
                          0x0f, 0x1f, 0x1f, 0x3f, 0x3f, 0x7f, 0x7f, 0xff))
  
  charset <- c(charset, rev(charset))
  charset <- rep(charset, each=8)
  charset <- rep(charset, times=8)
  
  # 256 characters. 8 bytes each
  stopifnot(length(charset) == 256 * 8)
  charset
}



```



```{r}
#-----------------------------------------------------------------------------
# creating a spiral character set where the pixels are set from the middle first
# and spiral out to completely fill the 8x8 grid
#-----------------------------------------------------------------------------
create_spiral_charset <- function() {
  
  #---------------------------------------------------------------------------
  # Define what (r)ight, (d)own, (l)eft, (u)p convert to in terms of 
  # position deltas in the x, y directions
  #---------------------------------------------------------------------------
  vec <- data_frame(
    direction = c('r', 'd', 'l', 'u'),
    x         = c( 1 ,  0 , -1 ,  0 ),
    y         = c( 0,  -1 ,  0 ,  1 )
  )
  
  #---------------------------------------------------------------------------
  # Basic spiral pattern
  #---------------------------------------------------------------------------
  spiral <- data_frame(
    direction = rep(c('r', 'd', 'l', 'u'), times=4),
    length    = rep(1:8, each=2)
  ) %>% left_join(vec, by='direction')
  
  #---------------------------------------------------------------------------
  # Unroll the spiral
  #---------------------------------------------------------------------------
  spiral %<>% 
    slice(rep(seq(nrow(.)), times=.$length))
  
  #---------------------------------------------------------------------------
  # Work out the x,y of each pixel
  #---------------------------------------------------------------------------
  spiral %<>%
    add_row(x=4, y=5, .before = 1) %>%
    mutate(
      x = cumsum(x), 
      y = cumsum(y)
    )
  
  #---------------------------------------------------------------------------
  # Trim to just 64 pixels (8x8 charset)
  #---------------------------------------------------------------------------
  spiral %<>%
    select(x, y) %>%
    head(64)
  
  
  #---------------------------------------------------------------------------
  # Helper to conver:  c(0, 0, 0, 1, 1, 0, 0, 0) -> 24
  #---------------------------------------------------------------------------
  row_to_byte <- function(row) {
    as.integer(sum(2^(7:0) * (row > 0)))
  }
  
  
  #---------------------------------------------------------------------------
  # Create character 'n' in the spiral sequence
  #---------------------------------------------------------------------------
  create_char <- function(n) {
    char <- matrix(0L, nrow = 8, ncol=8)
    for (i in seq_len(n)) {
      char[spiral$y[i], spiral$x[i]] <- 1
    }
    # char
    apply(char, 1, row_to_byte)
  }
  
  
  #---------------------------------------------------------------------------
  # Create the character set
  #---------------------------------------------------------------------------
  charset <- seq(0, 64) %>% purrr::map(create_char) 
  
  #---------------------------------------------------------------------------
  # Create the reverse sequence
  #---------------------------------------------------------------------------
  charset_rev <- rev(charset) %>% head(-1) %>% tail(-1)
  
  #---------------------------------------------------------------------------
  # Combine forwards and reverse spirals, repeat chars as necessary
  #---------------------------------------------------------------------------
  charset <- rep(c(charset, charset_rev), times=2)
  charset <- purrr::flatten_int(charset)
  
  # 256 characters. 8 bytes each
  stopifnot(length(charset) == 256 * 8)
  charset
}

charset <- create_spiral_charset()
```


```{r}
create_sine_screen <- function() {
  screen_state  <- expand.grid(x=1:40, y=1:25) %>%
    as.tbl() %>%
    mutate(
      x = (x - 21  ) / (40-1),
      y = (y - 13.5) / (25-1),
      z = sin(4 * sqrt(x^2 + y^2)),
      z = (z - min(z)) / (max(z) - min(z)),
      z = as.integer(z * 255)
    )
  screen_state$z
}

create_scroll_screen <- function() {
  as.integer(1:1000 %% 256)
}


screen_state  <- create_sine_screen()
screen_state  <- create_scroll_screen()

screen_state1 <- screen_state[  1: 250]
screen_state2 <- screen_state[251: 500]
screen_state3 <- screen_state[501: 750]
screen_state4 <- screen_state[751:1000]
```





```{r}
asm <- '*=$0801
.byte $0c, $08, $0a, $00, $9e, $20
.byte $32, $30, $38, $30, $00, $00
.byte $00
*=$0820
           sei          ; turn off interrupts
           lda #$7f
           ldx #$01
           sta $dc0d    ; Turn off CIA 1 interrupts
           sta $dd0d    ; Turn off CIA 2 interrupts
           stx $d01a    ; Turn on raster interrupts

           lda #$1b
           ldx #$08
           ldy #$14
           sta $d011    ; Clear high bit of $d012, set text mode
           stx $d016    ; single-colour
           sty $d018    ; screen at $0400, charset at $2000

           lda $d018    ; Changing character set to $3800 - $3800 + $800 (2048 bytes)
           and #$f0
           ora #$08
           sta $d018

           lda #$01     ; set background colour
           sta $d020
           sta $d021

           jsr initscr
           jsr initcolour


           lda #<int    ; low part of address of interrupt handler code
           ldx #>int    ; high part of address of interrupt handler code
           ldy #$80     ; line to trigger interrupt
           sta $0314    ; store in interrupt vector
           stx $0315
           sty $d012

           lda $dc0d    ; ACK CIA 1 interrupts
           lda $dd0d    ; ACK CIA 2 interrupts
           asl $d019    ; ACK VIC interrupts
           cli

loop:
           jmp loop     ; infinite loop




;--------------------------------------------------------------
; Initialise screen 
;--------------------------------------------------------------
initscr:
		       ldx #$fa
scrloop:
           lda screen1, x
           sta $03ff,x
           lda screen2, x
           sta $04f9,x
           lda screen3, x
           sta $05f3,x
           lda screen4, x
           sta $06ed,x
           dex
           bne scrloop

           rts

initcolour: 
		       ldx #$00
           lda #$00
colourloop:
           sta $d800,x
           sta $d8fa,x
           sta $d9f4,x
           sta $daee,x
           inx
           cpx #$fa
           bne colourloop
           rts



;--------------------------------------------------------------
; Inrement every character on the screen. 
; Race behind the raster so we dont get any screen tearing
;--------------------------------------------------------------
incscreen:
		       ldx #$fa
incscr1:
           inc $03ff,x
           dex
           bne incscr1
		       ldx #$fa
incscr2:
           inc $04f9,x
           dex
           bne incscr2
		       ldx #$fa
incscr3:
           inc $05f3,x
           dex
           bne incscr3
		       ldx #$fa
incscr4:
           inc $06ed,x
           dex
           bne incscr4

           rts


;--------------------------------------------------------------
; Interupt routine
;--------------------------------------------------------------
int:
           ;inc $d020    ; increment border colour

           jsr incscreen

           ;dec $d020    ; decrement border colour

           asl $d019    ; ACK interrupt (to re-enable it)

           pla          ; prepare to return from interupt
           tay
           pla
           tax
           pla
           rti          ; return from interrupt


screen1   .rbyte screen_state1
screen2   .rbyte screen_state2
screen3   .rbyte screen_state3
screen4   .rbyte screen_state4

;--------------------------------------------------------------
; Load in a charset from R
;--------------------------------------------------------------
* = $2000
          .rbyte charset

'


```



```{r}
library(r64)
line_tokens <- r64::create_line_tokens(asm)
prg_df <- r64::create_prg_df(line_tokens)

prg_df 
```


```{r}
prg_df <- r64::process_xrefs(prg_df)
prg_df
```

```{r}
prg_df <- r64::process_zero_padding(prg_df)
prg_df
```



```{r}
if (TRUE) {
  outfile <- tempfile()
  r64::save_prg(prg_df, outfile)
  system(paste("/usr/local/opt/vice/x64.app/Contents/MacOS/x64", outfile), wait=FALSE)
}
```

